"""Building and verifying the committed `.method/` snapshot.

The snapshot is the layer that makes a plugin-delivered methodology
self-contained. It holds the full rule text and the linters, it is
committed, and it is never edited by hand — editing it would recreate the
copy drift the plugin exists to remove.

Three operations:

- `sync`   rebuild the snapshot from this plugin
- `verify` recompute the content hash and compare (the CI gate)
- `status` compare the snapshot's version against the installed plugin

    python method_sync.py sync
    python method_sync.py verify
"""
import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

import notes_config

PLUGIN_ROOT = Path(os.environ.get("CLAUDE_PLUGIN_ROOT", Path(__file__).resolve().parent.parent))

# method_sync itself is included: CI runs `verify` out of the snapshot,
# on a checkout that has no plugin installed. Verification only needs the
# recorded hash and the files, so it works standalone.
SNAPSHOT_SCRIPTS = (
    "notes_config.py",
    "check_docs.py",
    "marker_scan.py",
    "method_sync.py",
    "notes_survey.py",
)

# The hooks travel in the snapshot too. Enforcement that lives only inside
# the plugin stops at the machines that happen to have it installed, and a
# repository whose rules are not being enforced looks exactly like one whose
# rules are. hooks.json is deliberately not here: registration is the
# repository's `.claude/settings.json`, and a second copy of it in the
# snapshot would be a file nobody reads.
SNAPSHOT_HOOKS = (
    "hook_io.py",
    "gate_rules.py",
    "session_report.py",
    "session_close.py",
    "doc_followup.py",
    "incoming.py",
    "session-start.py",
    "user-prompt-submit.py",
    "pre-tool-use.py",
    "post-tool-use.py",
    "stop.py",
    "run-hook.cmd",
)

# The shell Claude Code picks invokes the wrapper directly, so on Linux and
# macOS it needs the execute bit.
EXECUTABLE_IN_SNAPSHOT = "run-hook.cmd"

# The five events, each with the matcher and timeout it needs. Here rather
# than in the settings template because the command has to name this
# repository's own snapshot path, and a JSON template with every brace
# doubled for str.format is a file nobody can read or edit safely.
HOOK_EVENTS = (
    ("SessionStart", "session-start", "startup|resume|clear|compact", 30),
    ("UserPromptSubmit", "user-prompt-submit", None, 10),
    ("PreToolUse", "pre-tool-use", "Bash|Edit|Write|MultiEdit|NotebookEdit", 15),
    ("PostToolUse", "post-tool-use", "Edit|Write|MultiEdit|NotebookEdit|Bash", 20),
    ("Stop", "stop", None, 30),
)

# Running the snapshot's own scripts drops __pycache__ next to them, which
# would change the content hash and make the CI gate fail on its own side
# effect. Generated bytecode is not part of the snapshot.
IGNORED_IN_SNAPSHOT = ("__pycache__",)

GITIGNORE = """__pycache__/
*.pyc
"""

SKILL_ORDER = (
    "project-notes",
    "progress-board",
    "writing-adr",
    "doc-style",
    "parallel-docs",
    "safety-gate",
)

GATE_BLOCK = """\
> [!CAUTION]
> ## 작업 전 필수 확인 — 통과 못 하면 어떤 편집도 하지 않는다
>
> 1. 이 파일(`.method/RULES.md`)과 `.method/VERSION` 이 저장소에 있는가?
>    없으면 **작업을 중단**하고 사용자에게 알린다.
> 2. Claude Code 라면 세션 시작 주입 블록 `[girok] ready vX.Y.Z` 가 이 세션에
>    있는가? 없으면 검사가 돌고 있지 않은 것이다 — **작업을 중단**하고 알린다.
>    셋 중 하나다: 폴더 신뢰 미승인, 이 머신에 Python 없음, 스냅샷이 낡아 훅이
>    등록되지 않음(`/notes` 로 sync).
> 3. 다른 에이전트라면 이 파일을 **끝까지 읽은 뒤에만** 작업한다. 아래가 규칙 전문이다.
>
> 이 확인을 건너뛰고 편집하면 규칙이 적용되지 않은 채로 기록이 쌓인다 — 그 사실을
> 나중에 알아낼 방법이 없다. 훅은 이 저장소가 `.claude/settings.json` 에서 등록하므로
> 플러그인 없이도 돈다.
"""


class NoPluginError(Exception):
    """sync was asked to rebuild from something that is not the plugin.

    PLUGIN_ROOT falls back to this file's own grandparent, which for the
    snapshot's copy is `.method/` itself. sync deletes that folder before
    rebuilding, so on a machine with no plugin the fallback pointed it at its
    own sources: it removed every hook and linter, found nothing to copy
    back, and reported success. The check has to run before anything is
    deleted.
    """


class SettingsUnreadable(Exception):
    """`.claude/settings.json` is there but could not be parsed.

    Refusing to overwrite half-edited JSON is right. Saying nothing about it
    is not -- the snapshot lands, the hooks never register, and the run reads
    as a clean success.
    """


class NotOursError(Exception):
    """`.method/` exists but was not written by this plugin.

    sync rebuilds that folder by deleting it first. A repository that happens
    to keep something else at the same path would lose it, so the folder must
    identify itself — a VERSION file naming this plugin — before anything is
    removed.
    """


@dataclass
class Version:
    plugin_version: str
    date: str
    commit: str
    content_hash: str

    def render(self) -> str:
        return (
            f"girok v{self.plugin_version} / {self.date} / "
            f"{self.commit} / {self.content_hash}\n"
        )


@dataclass
class SyncResult:
    written: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    version: Version | None = None
    settings_changed: bool = False
    settings_problem: str | None = None


@dataclass
class VerifyResult:
    problems: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.problems


@dataclass
class Status:
    snapshot_version: str | None
    plugin_version: str | None

    @property
    def in_sync(self) -> bool:
        return (
            self.snapshot_version is not None
            and self.plugin_version is not None
            and self.snapshot_version == self.plugin_version
        )


def plugin_version(plugin_root: Path = PLUGIN_ROOT) -> str | None:
    """The installed plugin's version, or None where it is not installed.

    The snapshot carries the hooks now, so sessions run on machines with no
    plugin at all. Raising here took the whole session-start report down with
    it: a repository that was fully set up reported nothing, and the readiness
    marker it owes the CLAUDE.md gate never appeared.
    """
    manifest = plugin_root / ".claude-plugin" / "plugin.json"
    try:
        return json.loads(manifest.read_text(encoding="utf-8"))["version"]
    except (OSError, KeyError, json.JSONDecodeError):
        return None


def _plugin_commit(plugin_root: Path) -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=plugin_root, capture_output=True, text=True,
        )
    except OSError:
        return "unknown"
    return result.stdout.strip() if result.returncode == 0 else "unknown"


def build_rules(plugin_root: Path = PLUGIN_ROOT) -> str:
    """The full rule text as one file.

    Skills are Claude Code only. This file is the single channel every other
    agent has, so it carries the same content in reading order rather than a
    pointer back to the plugin.
    """
    parts = [
        "# 문서 방법론 규칙 전문",
        "",
        "> 이 파일은 `girok` 플러그인이 생성한 **동결 사본**이다.",
        "> 사람이 손으로 고치지 않는다 — 개정은 플러그인 원본에서 하고 sync 로 내려받는다.",
        "> 판본은 같은 폴더의 `VERSION` 참고.",
        "",
        GATE_BLOCK,
        "",
        "---",
        "",
    ]
    skills_dir = plugin_root / "skills"
    for name in SKILL_ORDER:
        skill = skills_dir / name / "SKILL.md"
        if not skill.is_file():
            continue
        body = skill.read_text(encoding="utf-8")
        if body.startswith("---"):
            body = body.split("---", 2)[2].lstrip("\n")
        parts.append(f"<!-- skill: {name} -->")
        parts.append("")
        parts.append(body.rstrip())
        parts.append("")
        parts.append("---")
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def notes_prefix(cfg: notes_config.NotesConfig) -> str:
    """The path from the repository root down to where `.method/` sits.

    Empty for a flat repository. The hook commands carry it, so getting it
    wrong registers a wrapper that is not there -- a hook that never runs and
    never says so.
    """
    try:
        rel = cfg.notes_dir.relative_to(cfg.repo_root).as_posix()
    except ValueError:
        return ""
    return "" if rel == "." else f"{rel}/"


def hook_settings(prefix: str) -> dict:
    """The hooks block that registers the snapshot's own copies.

    `${CLAUDE_PROJECT_DIR}` rather than the plugin root, which is the whole
    point: these have to run on a machine where no plugin root exists.
    """
    wrapper = f"${{CLAUDE_PROJECT_DIR}}/{prefix}.method/hooks/run-hook.cmd"
    events = {}
    for event, script, matcher, timeout in HOOK_EVENTS:
        entry = {} if matcher is None else {"matcher": matcher}
        entry["hooks"] = [
            {
                "type": "command",
                "command": f'"{wrapper}" {script}',
                "async": False,
                "timeout": timeout,
            }
        ]
        events[event] = [entry]
    return events


def sync_settings(root: Path, prefix: str, plugin_root: Path = PLUGIN_ROOT) -> bool:
    """Put the snapshot's hooks into the repository's own settings.

    Every repository that adopted girok before this already has a
    settings.json, and initialization skips a file that exists -- so the
    hooks would never arrive and the rules would sit there unenforced.

    Only the `hooks` key is written. Permissions and marketplace entries
    someone added by hand stay exactly as they are.
    """
    path = root / ".claude" / "settings.json"
    if path.is_file():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            # Overwriting half-edited JSON would take someone's work with it,
            # so this stops -- but loudly. The caller records the problem.
            raise SettingsUnreadable(
                f".claude/settings.json 을 읽을 수 없어 훅을 등록하지 못했다 ({exc}). "
                f"그 파일을 고친 뒤 다시 sync 할 것 — 지금은 규칙이 저장소에 있어도 "
                f"아무것도 검사하지 않는다"
            ) from exc
    else:
        data = _default_settings(plugin_root)

    registered = data.get("hooks") or {}
    merged = dict(registered)
    for event, entries in hook_settings(prefix).items():
        # Ours replaced, everyone else's kept. verify lets a repository
        # register hooks of its own, so sync deleting them was the two halves
        # of this design disagreeing -- and the first `/notes` after an
        # upgrade would silently stop somebody's logging hook.
        merged[event] = entries + [e for e in registered.get(event, []) if not _is_ours(e)]
    if merged == registered:
        return False

    data["hooks"] = merged
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8", newline="\n",
    )
    return True


WRAPPER_TAIL = ".method/hooks/run-hook.cmd"


def _is_ours(entry: dict) -> bool:
    """Whether a registration entry is one girok wrote.

    Matched on the wrapper's tail rather than the full path so that an entry
    left by an earlier layout -- a different notesDir, a renamed folder --
    is recognized and replaced instead of accumulating beside the new one.
    """
    return any(WRAPPER_TAIL in hook.get("command", "") for hook in entry.get("hooks", []))


def _runs_our_wrapper(command: str, wrapper: str) -> bool:
    """Whether the command runs this repository's wrapper.

    A plain substring test passed `vendor.notes/.method/hooks/run-hook.cmd`
    for a repository whose wrapper is `notes/.method/hooks/run-hook.cmd`: the
    entry reads as correct in the file and the hook never runs, which is the
    one failure this check exists to catch. The character in front of the
    match has to be a separator or the opening quote.
    """
    at = command.find(wrapper)
    while at != -1:
        if at == 0 or command[at - 1] in ("/", chr(92), '"', "'"):
            return True
        at = command.find(wrapper, at + 1)
    return False


def _default_settings(plugin_root: Path) -> dict:
    template = plugin_root / "templates" / "settings.json"
    try:
        return json.loads(template.read_text(encoding="utf-8").format())
    except (OSError, json.JSONDecodeError):
        return {}


def _registration_problems(cfg: notes_config.NotesConfig) -> list[str]:
    """Whether this repository's settings still register the snapshot's hooks.

    `.claude/settings.json` sits outside `.method/`, so the content hash
    cannot speak for it. Inside a session the missing ready marker catches a
    dropped registration -- but that marker comes from a hook, so something
    outside the session has to be able to see it too.

    Checked per event rather than by comparing the whole block: a repository
    is free to register hooks of its own, and failing it for that would push
    people to drop the check instead of the hook.
    """
    path = cfg.repo_root / ".claude" / "settings.json"
    if not path.is_file():
        return [
            ".claude/settings.json 없음 — 훅이 등록되지 않았다. "
            "규칙이 저장소에 있어도 아무것도 검사하지 않는다. `/notes` 로 sync 할 것"
        ]
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return [f".claude/settings.json 을 읽을 수 없다 ({exc})"]

    wrapper = f"{notes_prefix(cfg)}.method/hooks/run-hook.cmd"
    registered = data.get("hooks") or {}
    missing = []
    for event, script, _matcher, _timeout in HOOK_EVENTS:
        commands = [
            hook.get("command", "")
            for entry in registered.get(event, [])
            for hook in entry.get("hooks", [])
        ]
        if not any(_runs_our_wrapper(c, wrapper) and c.rstrip().endswith(script) for c in commands):
            missing.append(event)
    if missing:
        return [
            f".claude/settings.json 에 훅이 등록되지 않았다 ({', '.join(missing)}) — "
            f"등록이 없으면 규칙이 저장소에 있어도 아무것도 검사하지 않는다. "
            f"`/notes` 로 sync 할 것"
        ]
    return []


def _make_executable(path: Path, repo_root: Path) -> None:
    """Give the wrapper its execute bit, on disk and in the git index.

    Two separate things drop it. `shutil.copyfile` copies content and not
    mode, and git on Windows records a new file as 100644 with no way to say
    otherwise -- so a snapshot synced on Windows reaches a Linux checkout
    with a wrapper that is registered as a hook and cannot be run. Nothing
    reports that: the session looks supervised and is not.

    Both attempts are best-effort. On Windows chmod does not carry an execute
    bit, and a repository that has no git yet has no index to write to.
    """
    try:
        os.chmod(path, 0o755)
    except OSError:
        pass
    try:
        rel = path.relative_to(repo_root).as_posix()
    except ValueError:
        return
    try:
        subprocess.run(
            ["git", "update-index", "--add", "--chmod=+x", rel],
            cwd=repo_root, capture_output=True,
        )
    except OSError:
        pass


def _content_hash(method_dir: Path) -> str:
    """Hash of every file under `.method/` except VERSION itself.

    Paths go into the digest alongside the bytes so that renaming or
    deleting a file changes the hash. Line endings are normalized because a
    Windows checkout would otherwise never match a hash computed on Linux.
    """
    digest = hashlib.sha256()
    for path in sorted(method_dir.rglob("*")):
        if not path.is_file() or path.name == "VERSION" or _is_generated(path):
            continue
        digest.update(path.relative_to(method_dir).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes().replace(b"\r\n", b"\n"))
        digest.update(b"\0")
    return digest.hexdigest()


def _is_generated(path: Path) -> bool:
    return path.suffix == ".pyc" or any(part in IGNORED_IN_SNAPSHOT for part in path.parts)


def parse_version(text: str) -> Version:
    """Read a VERSION stamp. A truncated one yields empty fields rather than
    raising: this is called from the session-start report, and a half-written
    file must produce "the snapshot is off", not a failed hook."""
    head, *rest = [part.strip() for part in text.strip().split("/")]
    words = head.split()
    name_version = words[-1].lstrip("v") if words else ""
    return Version(
        plugin_version=name_version,
        date=rest[0] if len(rest) > 0 else "",
        commit=rest[1] if len(rest) > 1 else "",
        content_hash=rest[2] if len(rest) > 2 else "",
    )


def method_dir(cfg: notes_config.NotesConfig) -> Path:
    return cfg.notes_dir / ".method"


def _looks_like_ours(stamp: str) -> bool:
    """Whether a VERSION stamp was written by this plugin, current or renamed."""
    if "girok" in stamp:
        return True
    try:
        parsed = parse_version(stamp)
    except (ValueError, IndexError):
        return False
    return len(parsed.content_hash) == 64 and all(
        c in "0123456789abcdef" for c in parsed.content_hash
    )


def sync(start: Path | str = ".", plugin_root: Path = PLUGIN_ROOT) -> SyncResult:
    # Before anything is removed. sync rebuilds by deleting the folder first,
    # and the PLUGIN_ROOT fallback can point at that very folder.
    if not (plugin_root / ".claude-plugin" / "plugin.json").is_file():
        raise NoPluginError(
            f"{plugin_root} 는 girok 플러그인이 아니다 — sync 는 플러그인 원본에서만 돈다. "
            f"플러그인이 설치된 머신에서 `/notes` 로 실행할 것. "
            f"스냅샷은 손대지 않았다"
        )

    cfg = notes_config.load(start)
    target = method_dir(cfg)
    result = SyncResult()

    expected = (
        {"RULES.md", "VERSION", ".gitignore"}
        | {f"scripts/{n}" for n in SNAPSHOT_SCRIPTS}
        | {f"hooks/{n}" for n in SNAPSHOT_HOOKS}
    )

    if target.exists():
        version_file = target / "VERSION"
        # A snapshot from before the rename identifies itself with the old
        # plugin name. That name is deliberately not spelled here, so the
        # recognition is by shape instead: our VERSION stamp always ends in
        # a 64-hex content hash, which nothing else keeps at this path.
        stamp = (
            version_file.read_text(encoding="utf-8", errors="replace")
            if version_file.is_file()
            else ""
        )
        if not _looks_like_ours(stamp):
            raise NotOursError(
                f"{target} 가 이미 있는데 이 플러그인이 만든 것이 아니다 "
                f"(VERSION 파일이 없거나 다른 내용이다). 지우지 않고 멈춘다 — "
                f"그 폴더가 무엇인지 확인한 뒤 옮기거나 지우고 다시 실행할 것"
            )
        for path in sorted(target.rglob("*")):
            if path.is_file() and not _is_generated(path):
                rel = path.relative_to(target).as_posix()
                if rel not in expected:
                    result.removed.append(rel)
        shutil.rmtree(target)

    (target / "scripts").mkdir(parents=True, exist_ok=True)
    (target / "hooks").mkdir(parents=True, exist_ok=True)
    (target / ".gitignore").write_text(GITIGNORE, encoding="utf-8", newline="\n")
    (target / "RULES.md").write_text(build_rules(plugin_root), encoding="utf-8", newline="\n")
    result.written.extend(["RULES.md", ".gitignore"])
    for name in SNAPSHOT_SCRIPTS:
        source = plugin_root / "scripts" / name
        if source.is_file():
            shutil.copyfile(source, target / "scripts" / name)
            result.written.append(f"scripts/{name}")
    for name in SNAPSHOT_HOOKS:
        source = plugin_root / "hooks" / name
        if source.is_file():
            copy = target / "hooks" / name
            shutil.copyfile(source, copy)
            if name == EXECUTABLE_IN_SNAPSHOT:
                _make_executable(copy, cfg.repo_root)
            result.written.append(f"hooks/{name}")

    version = Version(
        plugin_version=plugin_version(plugin_root),
        date=date.today().isoformat(),
        commit=_plugin_commit(plugin_root),
        content_hash=_content_hash(target),
    )
    (target / "VERSION").write_text(version.render(), encoding="utf-8", newline="\n")
    result.version = version

    # Registration belongs with the copy. Split in two, a repository could
    # sit with the hooks committed and nothing registering them.
    try:
        result.settings_changed = sync_settings(cfg.repo_root, notes_prefix(cfg), plugin_root)
    except SettingsUnreadable as exc:
        result.settings_problem = str(exc)
    return result


def verify(start: Path | str = ".") -> VerifyResult:
    """The CI gate (D14): the snapshot must be byte-identical to what the
    plugin revision in VERSION produces.

    Local hooks only protect people who have the plugin installed. Anyone
    without it, another agent, or an edit made through a web UI reaches the
    repository unchecked — so this runs on every push.
    """
    cfg = notes_config.load(start)
    target = method_dir(cfg)
    result = VerifyResult()

    if not target.is_dir():
        result.problems.append(f"{target} 없음 — `/notes` 로 초기화할 것")
        return result

    version_file = target / "VERSION"
    if not version_file.is_file():
        result.problems.append(f"{version_file} 없음 — 스냅샷이 손상됨")
        return result

    recorded = parse_version(version_file.read_text(encoding="utf-8"))
    actual = _content_hash(target)
    if actual != recorded.content_hash:
        changed = _changed_files(target, recorded)
        detail = f" — {', '.join(changed)}" if changed else ""
        result.problems.append(
            f".method/ 내용이 VERSION 의 해시와 다름{detail}. "
            f"사람이 손댔거나 sync 가 낡음 — 개정은 플러그인 원본에서 하고 다시 sync 할 것"
        )
    result.problems.extend(_registration_problems(cfg))
    return result


def _changed_files(target: Path, recorded: Version) -> list[str]:
    """Name the files that differ from a fresh build, to make the failure
    actionable instead of just 'the hash is wrong'.

    Only possible where the plugin source is present. CI runs `verify` out of
    the snapshot on a checkout with no plugin installed, and comparing against
    a build with no skills to read named RULES.md as the culprit every time —
    a confident wrong answer in place of no answer.
    """
    if not (PLUGIN_ROOT / "skills").is_dir():
        return []
    try:
        fresh_rules = build_rules()
    except OSError:
        return []
    changed = []
    rules = target / "RULES.md"
    if rules.is_file() and rules.read_text(encoding="utf-8") != fresh_rules:
        changed.append("RULES.md")
    for folder, names in (("scripts", SNAPSHOT_SCRIPTS), ("hooks", SNAPSHOT_HOOKS)):
        for name in names:
            source = PLUGIN_ROOT / folder / name
            copy = target / folder / name
            if not copy.is_file():
                changed.append(f"{folder}/{name} (없음)")
            elif source.is_file() and _normalized(copy) != _normalized(source):
                changed.append(f"{folder}/{name}")
    return changed


def _normalized(path: Path) -> bytes:
    """File bytes with line endings flattened, the way the content hash reads
    them -- a Windows checkout must not look edited to a Linux runner."""
    return path.read_bytes().replace(b"\r\n", b"\n")


def status(start: Path | str = ".", plugin_root: Path = PLUGIN_ROOT) -> Status:
    cfg = notes_config.load(start)
    version_file = method_dir(cfg) / "VERSION"
    # An unreadable or empty stamp is reported as "no snapshot" rather than as
    # a version. The session-start gate keys off that: a corrupt snapshot must
    # not emit the ready marker, because the marker is what says the rules are
    # in force.
    snapshot = None
    if version_file.is_file():
        try:
            stamp = version_file.read_text(encoding="utf-8", errors="replace")
        except OSError:
            stamp = ""
        # A stamp without our 64-hex content hash is not a version we wrote.
        # Taking the last word of whatever the file holds announced
        # `ready vdata` for a VERSION reading "corrupt data" -- the gate
        # accepted a snapshot nobody had checked.
        parsed = parse_version(stamp)
        if len(parsed.content_hash) == 64:
            snapshot = parsed.plugin_version or None
    return Status(snapshot_version=snapshot, plugin_version=plugin_version(plugin_root))


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("action", choices=["sync", "verify", "status"])
    parser.add_argument("--root", type=Path, default=Path("."))
    args = parser.parse_args(argv)

    if args.action == "sync":
        result = sync(args.root)
        for rel in result.removed:
            print(f"[제거] 스냅샷에 없어야 할 파일: {rel}")
        if result.settings_problem:
            print(f"[실패] {result.settings_problem}")
        elif result.settings_changed:
            print("[등록] .claude/settings.json 에 훅 5종 — 커밋해야 다른 머신에도 걸린다")
        print(f"[완료] {len(result.written)}개 파일, {result.version.render().strip()}")
        return 0

    if args.action == "verify":
        result = verify(args.root)
        for problem in result.problems:
            print(f"[실패] {problem}")
        if result.problems:
            return 1
        print(".method/ 무결성 통과")
        return 0

    state = status(args.root)
    if state.snapshot_version is None:
        print("[경고] .method/ 스냅샷 없음 — `/notes` 로 초기화할 것")
        return 1
    # Having nothing to compare against is not the same as disagreeing. On a
    # machine without the plugin the snapshot is the only authority there is.
    if state.plugin_version is None:
        print(f"스냅샷 v{state.snapshot_version} — 플러그인이 없어 대조는 건너뛴다")
        return 0
    if not state.in_sync:
        print(
            f"[경고] 스냅샷 v{state.snapshot_version} vs 플러그인 v{state.plugin_version} — "
            f"`/notes` 로 sync 할 것"
        )
        return 1
    print(f"스냅샷 v{state.snapshot_version} — 플러그인과 일치")
    return 0


if __name__ == "__main__":
    sys.exit(main())
