"""Building and verifying the committed `.method/` snapshot.

The snapshot is the layer that makes a plugin-delivered methodology
self-contained. It holds the full rule text and the linters, it is
committed, and it is never edited by hand — editing it would recreate the
copy drift the plugin exists to remove.

Three operations:

- `sync`   rebuild the snapshot from this plugin
- `verify` recompute the content hash and compare (the CI gate)
- `status` compare the snapshot's version against the installed plugin

    python method_sync.py sync
    python method_sync.py verify
"""
import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

import notes_config

PLUGIN_ROOT = Path(os.environ.get("CLAUDE_PLUGIN_ROOT", Path(__file__).resolve().parent.parent))

# method_sync itself is included: CI runs `verify` out of the snapshot,
# on a checkout that has no plugin installed. Verification only needs the
# recorded hash and the files, so it works standalone.
SNAPSHOT_SCRIPTS = (
    "notes_config.py",
    "check_docs.py",
    "marker_scan.py",
    "method_sync.py",
    "notes_survey.py",
)

# The hooks travel in the snapshot too. Enforcement that lives only inside
# the plugin stops at the machines that happen to have it installed, and a
# repository whose rules are not being enforced looks exactly like one whose
# rules are. hooks.json is deliberately not here: registration is the
# repository's `.claude/settings.json`, and a second copy of it in the
# snapshot would be a file nobody reads.
SNAPSHOT_HOOKS = (
    "hook_io.py",
    "gate_rules.py",
    "session_report.py",
    "session_close.py",
    "doc_followup.py",
    "incoming.py",
    "session-start.py",
    "user-prompt-submit.py",
    "pre-tool-use.py",
    "post-tool-use.py",
    "stop.py",
    "run-hook.cmd",
)

# The shell Claude Code picks invokes the wrapper directly, so on Linux and
# macOS it needs the execute bit.
EXECUTABLE_IN_SNAPSHOT = "run-hook.cmd"

# Running the snapshot's own scripts drops __pycache__ next to them, which
# would change the content hash and make the CI gate fail on its own side
# effect. Generated bytecode is not part of the snapshot.
IGNORED_IN_SNAPSHOT = ("__pycache__",)

GITIGNORE = """__pycache__/
*.pyc
"""

SKILL_ORDER = (
    "project-notes",
    "progress-board",
    "writing-adr",
    "doc-style",
    "parallel-docs",
    "safety-gate",
)

GATE_BLOCK = """\
> [!CAUTION]
> ## 작업 전 필수 확인 — 통과 못 하면 어떤 편집도 하지 않는다
>
> 1. 이 파일(`.method/RULES.md`)과 `.method/VERSION` 이 저장소에 있는가?
>    없으면 **작업을 중단**하고 사용자에게 폴더 신뢰 승인과 플러그인 설치를 요청한다.
> 2. Claude Code 라면 세션 시작 주입 블록 `[girok] ready vX.Y.Z` 가 이 세션에
>    있는가? 없으면 플러그인이 로드되지 않은 것이다 — **작업을 중단**하고 알린다.
> 3. 다른 에이전트라면 이 파일을 **끝까지 읽은 뒤에만** 작업한다. 아래가 규칙 전문이다.
>
> 이 확인을 건너뛰고 편집하면 규칙이 적용되지 않은 채로 기록이 쌓인다 — 그 사실을
> 나중에 알아낼 방법이 없다.
"""


class NotOursError(Exception):
    """`.method/` exists but was not written by this plugin.

    sync rebuilds that folder by deleting it first. A repository that happens
    to keep something else at the same path would lose it, so the folder must
    identify itself — a VERSION file naming this plugin — before anything is
    removed.
    """


@dataclass
class Version:
    plugin_version: str
    date: str
    commit: str
    content_hash: str

    def render(self) -> str:
        return (
            f"girok v{self.plugin_version} / {self.date} / "
            f"{self.commit} / {self.content_hash}\n"
        )


@dataclass
class SyncResult:
    written: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    version: Version | None = None


@dataclass
class VerifyResult:
    problems: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.problems


@dataclass
class Status:
    snapshot_version: str | None
    plugin_version: str | None

    @property
    def in_sync(self) -> bool:
        return (
            self.snapshot_version is not None
            and self.plugin_version is not None
            and self.snapshot_version == self.plugin_version
        )


def plugin_version(plugin_root: Path = PLUGIN_ROOT) -> str | None:
    """The installed plugin's version, or None where it is not installed.

    The snapshot carries the hooks now, so sessions run on machines with no
    plugin at all. Raising here took the whole session-start report down with
    it: a repository that was fully set up reported nothing, and the readiness
    marker it owes the CLAUDE.md gate never appeared.
    """
    manifest = plugin_root / ".claude-plugin" / "plugin.json"
    try:
        return json.loads(manifest.read_text(encoding="utf-8"))["version"]
    except (OSError, KeyError, json.JSONDecodeError):
        return None


def _plugin_commit(plugin_root: Path) -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=plugin_root, capture_output=True, text=True,
        )
    except OSError:
        return "unknown"
    return result.stdout.strip() if result.returncode == 0 else "unknown"


def build_rules(plugin_root: Path = PLUGIN_ROOT) -> str:
    """The full rule text as one file.

    Skills are Claude Code only. This file is the single channel every other
    agent has, so it carries the same content in reading order rather than a
    pointer back to the plugin.
    """
    parts = [
        "# 문서 방법론 규칙 전문",
        "",
        "> 이 파일은 `girok` 플러그인이 생성한 **동결 사본**이다.",
        "> 사람이 손으로 고치지 않는다 — 개정은 플러그인 원본에서 하고 sync 로 내려받는다.",
        "> 판본은 같은 폴더의 `VERSION` 참고.",
        "",
        GATE_BLOCK,
        "",
        "---",
        "",
    ]
    skills_dir = plugin_root / "skills"
    for name in SKILL_ORDER:
        skill = skills_dir / name / "SKILL.md"
        if not skill.is_file():
            continue
        body = skill.read_text(encoding="utf-8")
        if body.startswith("---"):
            body = body.split("---", 2)[2].lstrip("\n")
        parts.append(f"<!-- skill: {name} -->")
        parts.append("")
        parts.append(body.rstrip())
        parts.append("")
        parts.append("---")
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def _make_executable(path: Path, repo_root: Path) -> None:
    """Give the wrapper its execute bit, on disk and in the git index.

    Two separate things drop it. `shutil.copyfile` copies content and not
    mode, and git on Windows records a new file as 100644 with no way to say
    otherwise -- so a snapshot synced on Windows reaches a Linux checkout
    with a wrapper that is registered as a hook and cannot be run. Nothing
    reports that: the session looks supervised and is not.

    Both attempts are best-effort. On Windows chmod does not carry an execute
    bit, and a repository that has no git yet has no index to write to.
    """
    try:
        os.chmod(path, 0o755)
    except OSError:
        pass
    try:
        rel = path.relative_to(repo_root).as_posix()
    except ValueError:
        return
    try:
        subprocess.run(
            ["git", "update-index", "--add", "--chmod=+x", rel],
            cwd=repo_root, capture_output=True,
        )
    except OSError:
        pass


def _content_hash(method_dir: Path) -> str:
    """Hash of every file under `.method/` except VERSION itself.

    Paths go into the digest alongside the bytes so that renaming or
    deleting a file changes the hash. Line endings are normalized because a
    Windows checkout would otherwise never match a hash computed on Linux.
    """
    digest = hashlib.sha256()
    for path in sorted(method_dir.rglob("*")):
        if not path.is_file() or path.name == "VERSION" or _is_generated(path):
            continue
        digest.update(path.relative_to(method_dir).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes().replace(b"\r\n", b"\n"))
        digest.update(b"\0")
    return digest.hexdigest()


def _is_generated(path: Path) -> bool:
    return path.suffix == ".pyc" or any(part in IGNORED_IN_SNAPSHOT for part in path.parts)


def parse_version(text: str) -> Version:
    """Read a VERSION stamp. A truncated one yields empty fields rather than
    raising: this is called from the session-start report, and a half-written
    file must produce "the snapshot is off", not a failed hook."""
    head, *rest = [part.strip() for part in text.strip().split("/")]
    words = head.split()
    name_version = words[-1].lstrip("v") if words else ""
    return Version(
        plugin_version=name_version,
        date=rest[0] if len(rest) > 0 else "",
        commit=rest[1] if len(rest) > 1 else "",
        content_hash=rest[2] if len(rest) > 2 else "",
    )


def method_dir(cfg: notes_config.NotesConfig) -> Path:
    return cfg.notes_dir / ".method"


def _looks_like_ours(stamp: str) -> bool:
    """Whether a VERSION stamp was written by this plugin, current or renamed."""
    if "girok" in stamp:
        return True
    try:
        parsed = parse_version(stamp)
    except (ValueError, IndexError):
        return False
    return len(parsed.content_hash) == 64 and all(
        c in "0123456789abcdef" for c in parsed.content_hash
    )


def sync(start: Path | str = ".", plugin_root: Path = PLUGIN_ROOT) -> SyncResult:
    cfg = notes_config.load(start)
    target = method_dir(cfg)
    result = SyncResult()

    expected = (
        {"RULES.md", "VERSION", ".gitignore"}
        | {f"scripts/{n}" for n in SNAPSHOT_SCRIPTS}
        | {f"hooks/{n}" for n in SNAPSHOT_HOOKS}
    )

    if target.exists():
        version_file = target / "VERSION"
        # A snapshot from before the rename identifies itself with the old
        # plugin name. That name is deliberately not spelled here, so the
        # recognition is by shape instead: our VERSION stamp always ends in
        # a 64-hex content hash, which nothing else keeps at this path.
        stamp = (
            version_file.read_text(encoding="utf-8", errors="replace")
            if version_file.is_file()
            else ""
        )
        if not _looks_like_ours(stamp):
            raise NotOursError(
                f"{target} 가 이미 있는데 이 플러그인이 만든 것이 아니다 "
                f"(VERSION 파일이 없거나 다른 내용이다). 지우지 않고 멈춘다 — "
                f"그 폴더가 무엇인지 확인한 뒤 옮기거나 지우고 다시 실행할 것"
            )
        for path in sorted(target.rglob("*")):
            if path.is_file() and not _is_generated(path):
                rel = path.relative_to(target).as_posix()
                if rel not in expected:
                    result.removed.append(rel)
        shutil.rmtree(target)

    (target / "scripts").mkdir(parents=True, exist_ok=True)
    (target / "hooks").mkdir(parents=True, exist_ok=True)
    (target / ".gitignore").write_text(GITIGNORE, encoding="utf-8", newline="\n")
    (target / "RULES.md").write_text(build_rules(plugin_root), encoding="utf-8", newline="\n")
    result.written.extend(["RULES.md", ".gitignore"])
    for name in SNAPSHOT_SCRIPTS:
        source = plugin_root / "scripts" / name
        if source.is_file():
            shutil.copyfile(source, target / "scripts" / name)
            result.written.append(f"scripts/{name}")
    for name in SNAPSHOT_HOOKS:
        source = plugin_root / "hooks" / name
        if source.is_file():
            copy = target / "hooks" / name
            shutil.copyfile(source, copy)
            if name == EXECUTABLE_IN_SNAPSHOT:
                _make_executable(copy, cfg.repo_root)
            result.written.append(f"hooks/{name}")

    version = Version(
        plugin_version=plugin_version(plugin_root),
        date=date.today().isoformat(),
        commit=_plugin_commit(plugin_root),
        content_hash=_content_hash(target),
    )
    (target / "VERSION").write_text(version.render(), encoding="utf-8", newline="\n")
    result.version = version
    return result


def verify(start: Path | str = ".") -> VerifyResult:
    """The CI gate (D14): the snapshot must be byte-identical to what the
    plugin revision in VERSION produces.

    Local hooks only protect people who have the plugin installed. Anyone
    without it, another agent, or an edit made through a web UI reaches the
    repository unchecked — so this runs on every push.
    """
    cfg = notes_config.load(start)
    target = method_dir(cfg)
    result = VerifyResult()

    if not target.is_dir():
        result.problems.append(f"{target} 없음 — `/notes` 로 초기화할 것")
        return result

    version_file = target / "VERSION"
    if not version_file.is_file():
        result.problems.append(f"{version_file} 없음 — 스냅샷이 손상됨")
        return result

    recorded = parse_version(version_file.read_text(encoding="utf-8"))
    actual = _content_hash(target)
    if actual != recorded.content_hash:
        changed = _changed_files(target, recorded)
        detail = f" — {', '.join(changed)}" if changed else ""
        result.problems.append(
            f".method/ 내용이 VERSION 의 해시와 다름{detail}. "
            f"사람이 손댔거나 sync 가 낡음 — 개정은 플러그인 원본에서 하고 다시 sync 할 것"
        )
    return result


def _changed_files(target: Path, recorded: Version) -> list[str]:
    """Name the files that differ from a fresh build, to make the failure
    actionable instead of just 'the hash is wrong'.

    Only possible where the plugin source is present. CI runs `verify` out of
    the snapshot on a checkout with no plugin installed, and comparing against
    a build with no skills to read named RULES.md as the culprit every time —
    a confident wrong answer in place of no answer.
    """
    if not (PLUGIN_ROOT / "skills").is_dir():
        return []
    try:
        fresh_rules = build_rules()
    except OSError:
        return []
    changed = []
    rules = target / "RULES.md"
    if rules.is_file() and rules.read_text(encoding="utf-8") != fresh_rules:
        changed.append("RULES.md")
    for folder, names in (("scripts", SNAPSHOT_SCRIPTS), ("hooks", SNAPSHOT_HOOKS)):
        for name in names:
            source = PLUGIN_ROOT / folder / name
            copy = target / folder / name
            if not copy.is_file():
                changed.append(f"{folder}/{name} (없음)")
            elif source.is_file() and _normalized(copy) != _normalized(source):
                changed.append(f"{folder}/{name}")
    return changed


def _normalized(path: Path) -> bytes:
    """File bytes with line endings flattened, the way the content hash reads
    them -- a Windows checkout must not look edited to a Linux runner."""
    return path.read_bytes().replace(b"\r\n", b"\n")


def status(start: Path | str = ".", plugin_root: Path = PLUGIN_ROOT) -> Status:
    cfg = notes_config.load(start)
    version_file = method_dir(cfg) / "VERSION"
    # An unreadable or empty stamp is reported as "no snapshot" rather than as
    # a version. The session-start gate keys off that: a corrupt snapshot must
    # not emit the ready marker, because the marker is what says the rules are
    # in force.
    snapshot = None
    if version_file.is_file():
        try:
            stamp = version_file.read_text(encoding="utf-8", errors="replace")
        except OSError:
            stamp = ""
        snapshot = parse_version(stamp).plugin_version or None
    return Status(snapshot_version=snapshot, plugin_version=plugin_version(plugin_root))


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("action", choices=["sync", "verify", "status"])
    parser.add_argument("--root", type=Path, default=Path("."))
    args = parser.parse_args(argv)

    if args.action == "sync":
        result = sync(args.root)
        for rel in result.removed:
            print(f"[제거] 스냅샷에 없어야 할 파일: {rel}")
        print(f"[완료] {len(result.written)}개 파일, {result.version.render().strip()}")
        return 0

    if args.action == "verify":
        result = verify(args.root)
        for problem in result.problems:
            print(f"[실패] {problem}")
        if result.problems:
            return 1
        print(".method/ 무결성 통과")
        return 0

    state = status(args.root)
    if state.snapshot_version is None:
        print("[경고] .method/ 스냅샷 없음 — `/notes` 로 초기화할 것")
        return 1
    # Having nothing to compare against is not the same as disagreeing. On a
    # machine without the plugin the snapshot is the only authority there is.
    if state.plugin_version is None:
        print(f"스냅샷 v{state.snapshot_version} — 플러그인이 없어 대조는 건너뛴다")
        return 0
    if not state.in_sync:
        print(
            f"[경고] 스냅샷 v{state.snapshot_version} vs 플러그인 v{state.plugin_version} — "
            f"`/notes` 로 sync 할 것"
        )
        return 1
    print(f"스냅샷 v{state.snapshot_version} — 플러그인과 일치")
    return 0


if __name__ == "__main__":
    sys.exit(main())
